dist: bionic
language: go

go:
  - "1.13"

branches:
  only:
    - master

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://goproxy.io

install: make bootstrap

after_success:
  # only report coverage for go-version 1.11
  - if [[ $TRAVIS_GO_VERSION =~ ^1\.11 ]] ; then bash <(curl -s https://codecov.io/bash) -f all-cover.txt; fi
